"use strict";
const express=require("express");const path=require("path");const QRCode=require("qrcode");const auth=require("./webAuth");const store=require("./webDashboardStore");const {startWhatsApp,activeSockets}=require("./whatsapp");
function requireUser(req,res,next){return auth.requireUser(req,res,next)}
function createDashboardApp(){const app=express();const pub=path.join(__dirname,"../public/dashboard");app.disable("x-powered-by");app.set("trust proxy",1);app.use(express.json({limit:"1mb"}));app.use("/dashboard",express.static(pub,{maxAge:"1h"}));app.get(["/api/healthz","/api/health"],(_q,r)=>r.json({status:"ok",nodes:activeSockets.size,ts:Date.now()}));auth.install(app);app.get("/",async(req,res,next)=>{try{if(await auth.current(req))return res.redirect("/app");res.sendFile(path.join(pub,"index.html"))}catch(e){next(e)}});app.get("/app",async(req,res,next)=>{try{(await auth.current(req))?res.sendFile(path.join(pub,"app.html")):res.redirect("/")}catch(e){next(e)}});
app.get('/api/me',requireUser,async(req,res,next)=>{try{res.json(await store.dashboard(req.webUser))}catch(e){next(e)}});
app.post('/api/pair',requireUser,async(req,res,next)=>{try{const account=await store.createAccount(req.webUser,req.body.phone);await startWhatsApp(req.webUser.id,account.phone_number,'1',false,0,req.webUser.id);await store.log(req.webUser,'pairing',`${account.phone_number} pairing requested from WEB`,'info',account.id);res.status(202).json({accountId:account.id,status:'pairing'})}catch(e){next(e)}});
app.get('/api/pair/:id/status',requireUser,async(req,res,next)=>{try{const account=await store.getAccount(req.webUser.id,req.params.id);if(!account)return res.status(404).json({error:'Pairing request not found'});const socket=activeSockets.get(account.session_key);let status=account.status;if(socket?._openedAt){status='connected';if(account.status!=='connected')await store.updateAccount(req.webUser.id,account.id,status)}const payload={status,code:socket?._pairingCodeValue||null,expiresIn:Math.max(0,120-Math.floor((Date.now()-(socket?._pairingCodeSentAt||Date.now()))/1000))};if(socket?._latestQr)payload.qr=await QRCode.toDataURL(socket._latestQr,{width:320,margin:2});res.json(payload)}catch(e){next(e)}});
app.post('/api/accounts/:id/action',requireUser,async(req,res,next)=>{try{await store.accountAction(req.webUser,req.params.id,String(req.body.action||''));res.json({ok:true})}catch(e){next(e)}});
app.post('/api/commands',requireUser,async(req,res,next)=>{try{const command=String(req.body.command||'').trim().slice(0,500);if(!command)return res.status(400).json({error:'Enter a command'});const account=await store.getAccount(req.webUser.id,req.body.accountId);if(!account)return res.status(404).json({error:'Select a paired account'});const socket=activeSockets.get(account.session_key);if(!socket?._openedAt)return res.status(409).json({error:'The selected account is not connected'});const key=command.split(/\s+/)[0].toLowerCase();const plugin=require('./commandRouter').plugins.get(key);if(!plugin)return res.status(404).json({error:`Unknown command: ${key}`});const target=`${socket.user.id.split(':')[0]}@s.whatsapp.net`;const msg={key:{remoteJid:target,fromMe:true,id:`web-${Date.now()}`},message:{conversation:command},pushName:req.webUser.github_username};const replies=await require('./pluginRunner').runPlugin({command:plugin,sock:socket,msg,args:command.split(/\s+/).slice(1),text:command,user:target,isGroup:false,botId:account.phone_number,commandName:key});const response=replies.join('\n')||'Command completed without a text response.';await store.saveCommand(req.webUser,account.id,command,response);res.json({response})}catch(e){next(e)}});
app.post('/api/links',requireUser,async(req,res,next)=>{try{res.json({links:await store.addLinks(req.webUser,req.body.text,'web')})}catch(e){next(e)}});
app.post('/api/radar',requireUser,async(req,res,next)=>{try{const target=String(req.body.target||'').trim();if(!/^https:\/\/(?:chat\.whatsapp\.com|whatsapp\.com\/channel)\//i.test(target))return res.status(400).json({error:'Enter a valid WhatsApp group or channel link'});res.json({scanId:await store.addScan(req.webUser,target),response:'Radar scan completed and synchronized.'})}catch(e){next(e)}});
app.post('/api/ai',requireUser,async(req,res,next)=>{try{const prompt=String(req.body.prompt||'').trim().slice(0,4000);if(!prompt)return res.status(400).json({error:'Enter a prompt'});const response=await require('./aiEngine').createAiEngine(req.webUser.id).complete({chatJid:`web:${req.webUser.id}`,prompt,senderName:req.webUser.github_username,botName:'PAPPY Web'});await store.log(req.webUser,'ai','AI web request completed');res.json({response})}catch(e){if(e.code==='NOT_CONFIGURED')return res.status(409).json({error:'Configure an AI provider in your PAPPY node first'});next(e)}});
app.put('/api/settings',requireUser,async(req,res,next)=>{try{await store.saveSettings(req.webUser,req.body);res.json({ok:true})}catch(e){next(e)}});
app.get('/api/export',requireUser,async(req,res,next)=>{try{res.attachment('pappy-web-export.json').json(await store.exportUserData(req.webUser))}catch(e){next(e)}});
app.use((err,_q,res,_n)=>{console.error('[Web]',err.message);res.status(err.status||500).json({error:err.status?err.message:'Dashboard request failed'})});app.use((_q,r)=>r.status(404).sendFile(path.join(pub,'index.html')));return app}
module.exports={createDashboardApp};
